version: '3'
services:
  app:
    image: napoleon-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  web:
    image: napoleon-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 80:80
    depends_on:
      - app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
